/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_github_nanodbc4j_internal_binding_jni_Native */

#ifndef _Included_io_github_nanodbc4j_internal_binding_jni_Native
#define _Included_io_github_nanodbc4j_internal_binding_jni_Native
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_github_nanodbc4j_internal_binding_jni_Native
 * Method:    getUtf16String
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_io_github_nanodbc4j_internal_binding_jni_Native_getUtf16String
  (JNIEnv *, jclass, jlong);

/*
 * Class:     io_github_nanodbc4j_internal_binding_jni_Native
 * Method:    std_free
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_io_github_nanodbc4j_internal_binding_jni_Native_std_1free
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
